#!/bin/sh /etc/rc.common
# Copyright (C) 2015
# Must keep author's information if you use this file.
#
# NTag dirty mod by @libc0607

START=50

HISTORY_DIR="/etc/config/guestwifi-ntagmod"
[ -e /etc/config/guestwifi-ntagmod ]||mkdir -p /etc/config/guestwifi-ntagmod

enabled=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].enable)
wifi_name=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].wifi_name)
interface_name=$(uci get guest-wifi.@guest-wifi[0].interface_name)
encryption=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].encryption)
passwd=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].passwd)
interface_ip=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].interface_ip)
isolate=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].isolate)
start=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].start)
limit=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].limit)
leasetime=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].leasetime)
device=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].device)
create=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].create)
use_ntag=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].use_ntag)
use_random_passwd=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].use_random_passwd)

start() {
	[ $enabled = 1 ] && {
		[ $create = 1 ] && {
			[ -f /etc/config/guestwifi-ntagmod/guest_del ] || echo "#! /bin/sh" > ${HISTORY_DIR}/guest_del
			chmod 0755 ${HISTORY_DIR}/guest_del
			[ -f /etc/config/guestwifi-ntagmod/guest_change_passwd ] || echo "#! /bin/sh" > ${HISTORY_DIR}/guest_change_passwd
			chmod 0755 ${HISTORY_DIR}/guest_change_passwd
			add_interface
			add_ssid
			mod_dhcp
			mod_fw
			/etc/init.d/network restart
		}
		uci set guest-wifi-ntagmod.@guest-wifi-ntagmod[0].create='0'
		uci commit guest-wifi-ntagmod
		uci del wireless.$interface_name.disabled
		uci commit wireless
		[ $use_random_passwd = 1 ] && {
			${HISTORY_DIR}/guest_change_passwd
		}
		wifi
		update_ntag
	}
}

stop() {
	[ $enabled = 0 ] && {
		[ $create = 1 ] && {
			${HISTORY_DIR}/guest_del
			rule_c=`uci show firewall |grep "Hide My LAN for $wifi_name"|grep -o "[0-9]*[0-9]"`
			uci del firewall.@rule[$rule_c]
			uci commit firewall
			rule_b=`uci show firewall |grep "Allow DHCP request for $wifi_name"|grep -o "[0-9]*[0-9]"`
			uci del firewall.@rule[$rule_b]
			uci commit firewall
			rule_a=`uci show firewall |grep "Allow DNS Queries for $wifi_name"|grep -o "[0-9]*[0-9]"`
			uci del firewall.@rule[$rule_a]
			uci commit firewall
			/etc/config/guestwifi-ntagmod/guest_del
			rm -rf /etc/config/guestwifi-ntagmod/guest_del
			rm -rf /etc/config/guestwifi-ntagmod/guest_change_passwd
			/etc/init.d/network restart
		}
		uci set guest-wifi-ntagmod.@guest-wifi-ntagmod[0].create='0'
		uci commit guest-wifi-ntagmod
		uci set wireless.$interface_name.disabled='1'
		uci commit wireless
		wifi
		format_ntag
	}
}

restart() {
	stop
	sleep 2
	start		
}

update_ntag() {
	[ $use_ntag = 1 ] && { 
		ntag_dev_path=$(fdisk -l|grep -s -B 1 "NFC ERRRROR"|grep -s /dev/sd*|cut -d ' ' -f 2|cut -d ':' -f 1)
		[ -e $ntag_dev_path ] && {
			ntag_path=$(mount|grep -s $ntag_dev_path|cut -d ' ' -f 3)
			[ -d $ntag_path ] && {
				echo "Ntag mounted at $ntag_path, updating..."
				pwd_volatile=$(uci get guest-wifi-ntagmod.@guest-wifi-ntagmod[0].passwd)
				[ -f $ntag_path/WIFISSID.TXT ] && echo -e "$wifi_name\r\n" > $ntag_path/WIFISSID.TXT
				[ -f $ntag_path/WIFIPWD.TXT ] && echo -e "$pwd_volatile\r\n" > $ntag_path/WIFIPWD.TXT
				if [ "$encryption" = "psk" ]; then
					[ -f $ntag_path/WIFIAUTH.TXT ] && echo -e "wpapsk\r\n" > $ntag_path/WIFIAUTH.TXT
					[ -f $ntag_path/WIFIENC.TXT ] && echo -e "aestkip\r\n" > $ntag_path/WIFIENC.TXT
				fi
				if [ "$encryption" = "psk2" ]; then
					[ -f $ntag_path/WIFIAUTH.TXT ] &&  echo -e "wpa2psk\r\n" > $ntag_path/WIFIAUTH.TXT
					[ -f $ntag_path/WIFIENC.TXT ] &&  echo -e "aestkip\r\n" > $ntag_path/WIFIENC.TXT
				fi
				if [ "$encryption" = "none" ]; then
					[ -f $ntag_path/WIFIAUTH.TXT ] && echo -e "open\r\n" > $ntag_path/WIFIAUTH.TXT
					[ -f $ntag_path/WIFIENC.TXT ] && echo -e "none\r\n" > $ntag_path/WIFIENC.TXT
				fi
				sync
				[ -f $ntag_path/SYNC.TXT ] && echo -e "1\r\n" > $ntag_path/SYNC.TXT
				sync
			}
		}			
	}
}

format_ntag() {
	[ $use_ntag = 1 ] && { 
		ntag_dev_path=$(fdisk -l|grep -s -B 1 "NFC ERRRROR"|grep -s /dev/sd*|cut -d ' ' -f 2|cut -d ':' -f 1)
		[ -e $ntag_dev_path ] && {
			ntag_path=$(mount|grep -s $ntag_dev_path|cut -d ' ' -f 3)
			[ -d $ntag_path ] && {
				echo "NTag mounted at $ntag_path, formatting..."
				[ -f $ntag_path/SYNC.TXT ] && echo -e "F\r\n" > $ntag_path/SYNC.TXT
				sync
			}
		}			
	}
}

add_interface() {
	name=`uci show network |grep "$interface_ip"`
	if [ $? = 1 ]; then
		uci set network.$interface_name=interface
		uci set network.$interface_name.proto='static'
		uci set network.$interface_name.ipaddr="$interface_ip"
		uci set network.$interface_name.netmask='255.255.255.0'
		echo "uci del network.$interface_name" >> ${HISTORY_DIR}/guest_del
		echo "uci commit network" >> ${HISTORY_DIR}/guest_del
		uci commit network
	fi
}

add_ssid() {
	check_name=`uci show wireless |grep "$wifi_name"`
	if [ $? = 1 ]; then
		uci set wireless.$interface_name=wifi-iface
		uci set wireless.$interface_name.device="$device"
		uci set wireless.$interface_name.mode='ap'
		uci set wireless.$interface_name.network="$interface_name"
		uci set wireless.$interface_name.ssid="$wifi_name"
		uci set wireless.$interface_name.encryption="$encryption"
		uci set wireless.$interface_name.isolate="$isolate"
		if [ "$encryption" != "none" ]; then
			uci set wireless.$interface_name.key="$passwd"
			echo "rand_pwd=\$(head -c 12 /dev/urandom | base64 | head -c 8)" >> ${HISTORY_DIR}/guest_change_passwd
			echo "echo \"New guest Wi-Fi password: \$rand_pwd\"" >> ${HISTORY_DIR}/guest_change_passwd
			echo "uci set wireless.$interface_name.key=\$rand_pwd" >> ${HISTORY_DIR}/guest_change_passwd
			echo "uci set guest-wifi-ntagmod.@guest-wifi-ntagmod[0].passwd=\$rand_pwd" >> ${HISTORY_DIR}/guest_change_passwd
			echo "uci commit wireless" >> ${HISTORY_DIR}/guest_change_passwd
			echo "uci commit guest-wifi-ntagmod" >> ${HISTORY_DIR}/guest_change_passwd
		fi
		echo "uci del wireless.$interface_name" >> ${HISTORY_DIR}/guest_del
		echo "uci commit wireless" >> ${HISTORY_DIR}/guest_del
		uci commit wireless
	fi
}

mod_dhcp() {
	check_dhcp=`uci show dhcp |grep "$interface_name=dhcp"`
	if [ $? = 1 ]; then
		uci set dhcp.$interface_name=dhcp
		uci set dhcp.$interface_name.interface="$interface_name"
		uci set dhcp.$interface_name.start="$start"
		uci set dhcp.$interface_name.limit="$limit"
		uci set dhcp.$interface_name.leasetime="$leasetime"
		echo "uci del dhcp.$interface_name" >> ${HISTORY_DIR}/guest_del
		echo "uci commit dhcp" >> ${HISTORY_DIR}/guest_del
		uci commit dhcp
	fi
}

mod_fw() {
	num_a=`uci show firewall |grep '=zone' |wc -l`
	num_b=`uci show firewall |grep '=forwarding' |wc -l`

	check_zone=`uci show firewall |grep "name=\'$interface_name\'"`
	if [ $? = 1 ]; then
		uci add firewall zone
		echo "uci del firewall.@zone[$num_a]" >> ${HISTORY_DIR}/guest_del
		echo "uci commit firewall" >> ${HISTORY_DIR}/guest_del
		uci set firewall.@zone[$num_a]=zone
		uci set firewall.@zone[$num_a].name="$interface_name"
		uci set firewall.@zone[$num_a].network="$interface_name"
		uci set firewall.@zone[$num_a].forward='REJECT'
		uci set firewall.@zone[$num_a].output='ACCEPT'
		uci set firewall.@zone[$num_a].input='REJECT'
		uci commit firewall
	fi

	check_forward=`uci show firewall |grep "forwarding\[.*\].src=\'"$interface_name\'""`
	if [ $? = 1 ]; then
		uci add firewall forwarding
		echo "uci del firewall.@forwarding[$num_b]" >> ${HISTORY_DIR}/guest_del
		echo "uci commit firewall" >> ${HISTORY_DIR}/guest_del
		uci set firewall.@forwarding[$num_b]=forwarding
		uci set firewall.@forwarding[$num_b].src="$interface_name"
		uci set firewall.@forwarding[$num_b].dest='wan'
		uci commit firewall
	fi

	check_DNS=`uci show firewall |grep "Allow DNS Queries for $wifi_name"`
	if [ $? = 1 ]; then
		num_c=`uci show firewall |grep '=rule' |wc -l`
		uci add firewall rule
		uci set firewall.@rule[$num_c]=rule
		uci set firewall.@rule[$num_c].name="Allow DNS Queries for $wifi_name"
		uci set firewall.@rule[$num_c].src="$interface_name"
		uci set firewall.@rule[$num_c].dest_port='53'
		uci set firewall.@rule[$num_c].proto='tcpudp'
		uci set firewall.@rule[$num_c].target='ACCEPT'
		uci commit firewall
		unset num_c
	fi

	check_DHCP=`uci show firewall |grep "Allow DHCP request for $wifi_name"`
	if [ $? = 1 ]; then
		num_c=`uci show firewall |grep '=rule' |wc -l`
		uci add firewall rule
		uci set firewall.@rule[$num_c]=rule
		uci set firewall.@rule[$num_c].name="Allow DHCP request for $wifi_name"
		uci set firewall.@rule[$num_c].src="$interface_name"
		uci set firewall.@rule[$num_c].src_port='67-68'
		uci set firewall.@rule[$num_c].dest_port='67-68'
		uci set firewall.@rule[$num_c].proto='udp'
		uci set firewall.@rule[$num_c].target='ACCEPT'
		uci commit firewall
		unset num_c
	fi

	check_HIDE=`uci show firewall |grep "Hide My LAN for $wifi_name"`
	if [ $? = 1 ]; then
		num_c=`uci show firewall |grep '=rule' |wc -l`
		uci add firewall rule
		uci set firewall.@rule[$num_c]=rule
		uci set firewall.@rule[$num_c].enabled='1'
		uci set firewall.@rule[$num_c].name="Hide My LAN for $wifi_name"
		uci set firewall.@rule[$num_c].proto='all'
		uci set firewall.@rule[$num_c].src="$interface_name"
		#convert netmask to cidr
		local lan_netmask=`uci get network.lan.netmask`
		local nbits=0
		local IFS=.
		for netmask_dec in $lan_netmask ; do
			case $netmask_dec in
				255) let nbits+=8 ;;
				254) let nbits+=7 ;;
				252) let nbits+=6 ;;
				248) let nbits+=5 ;;
				240) let nbits+=4 ;;
				224) let nbits+=3 ;;
				192) let nbits+=2 ;;
				128) let nbits+=1 ;;
				0) ;;
				*) echo "Error: $netmask_dec can not be recognised as netmask decimal." && exit 1 ;;
			esac
		done
		unset netmask_dec
		uci set firewall.@rule[$num_c].dest_ip="`uci get network.lan.ipaddr`/$nbits"
		uci set firewall.@rule[$num_c].target='REJECT'
		uci commit firewall
		unset num_c
	fi
}

